### **Data Preparation**

In [1]:
import pandas as pd
import numpy as np

##### **Dataset Cleaning**

In [2]:
dataset_csv = pd.read_csv('../data/Android_Malware.csv')

/tmp/ipykernel_55564/3928999249.py:1: DtypeWarning: Columns (56,58,63) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset_csv = pd.read_csv('../data/Android_Malware.csv')

*The warning shows that columns 56, 58, 63 have mixed dtypes. Thus, they need to be converted to appropriate dtype*

In [3]:
print(dataset_csv.iloc[:, 56].name)
dataset_csv.iloc[:, 56].unique()

 CWE Flag Count

array([0, nan, '0', 'SCAREWARE'], dtype=object)

*Since column 56 has only 0, nan, and unwanted string value, this feature doesn't provide any info, and thus can be dropped.*

In [4]:
columns_to_drop = [dataset_csv.columns[56]]

In [5]:
print(dataset_csv.iloc[:, 58].name)
dataset_csv.iloc[:, 58].unique()

 Down/Up Ratio

array([1.0, 0.0, 2.0, 3.0, 8.0, 4.0, 5.0, 9.0, 6.0, 12.0, 7.0, 10.0, 11.0,
       '1', '0', '7', '2', '3', '4', '11', '5', '12', '8', 'BENIGN', nan,
       75.0], dtype=object)

*Since column 58 has more than one numeric values, thus, it can be a useful feature. Thus, converting it to numeric dtype and removing rows with invalid values*

In [6]:
dataset_csv[dataset_csv.columns[58]] = dataset_csv.iloc[:, 58].apply(lambda x: pd.to_numeric(x, errors = 'ignore'))
dataset_csv[dataset_csv.columns[58]] = dataset_csv.iloc[:, 58].apply(lambda x: None if type(x) == str else x)
dataset_csv.dropna(inplace=True)
dataset_csv.drop_duplicates(inplace=True)
dataset_csv[dataset_csv.columns[58]].unique()

array([ 1.,  0.,  2.,  3.,  8.,  4.,  5.,  9.,  6., 12.,  7., 10., 11.,
       75.])

In [7]:
print(dataset_csv.iloc[:, 63].name)
dataset_csv.iloc[:, 63].unique()

Fwd Avg Bytes/Bulk

array([0, '0', '0.0'], dtype=object)

*Since column 63 also contains only 0 value, this column should be dropped. Also droppping the unamed [0] and flow id columns since they are used just for indexing*

In [8]:
if dataset_csv.columns[63] not in columns_to_drop : columns_to_drop.append(dataset_csv.columns[63])
if dataset_csv.columns[0] not in columns_to_drop : columns_to_drop.append(dataset_csv.columns[0])
if dataset_csv.columns[1] not in columns_to_drop : columns_to_drop.append(dataset_csv.columns[1])
columns_to_drop

[' CWE Flag Count', 'Fwd Avg Bytes/Bulk', 'Unnamed: 0', 'Flow ID']

In [9]:
dataset_csv.drop(columns=columns_to_drop, inplace=True, errors='ignore')
dataset_csv.dropna(inplace=True)
dataset_csv.drop_duplicates(inplace=True)
dataset_csv.shape

(351513, 82)

In [10]:
def clean_minus_one(i):
    if i == -1: return 0
    else: return i

In [15]:
dataset_csv[' Init_Win_bytes_backward'] = dataset_csv[' Init_Win_bytes_backward'].apply(clean_minus_one)
dataset_csv[' Init_Win_bytes_backward']

0           362.0
1           362.0
2         63441.0
3             0.0
4         64022.0
           ...
355625     1369.0
355626        0.0
355627       31.0
355628        0.0
355629        0.0
Name:  Init_Win_bytes_backward, Length: 351513, dtype: float64

In [16]:
dataset_csv.rename(columns=lambda x: x.strip(), inplace=True)

*Exporting the cleaned dataset for use*

In [17]:
dataset_csv.to_parquet('../data/variables/dataset_cleaned')

##### **Setting up variables**

In [18]:
dataset = pd.read_parquet('../data/variables/dataset_cleaned')
dataset

,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,10.42.0.211,50004,172.217.6.202,443.0,6.0,13/06/2017 11:52:39,37027,1,1,0.0,...,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware
1,10.42.0.211,35455,172.217.6.202,443.0,6.0,13/06/2017 11:52:39,36653,1,1,0.0,...,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware
2,10.42.0.211,51775,131.253.61.68,443.0,6.0,13/06/2017 11:52:42,534099,8,12,1011.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware
3,10.42.0.211,51775,131.253.61.68,443.0,6.0,13/06/2017 11:52:43,9309,3,0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware
4,10.42.0.211,51776,131.253.61.68,443.0,6.0,13/06/2017 11:52:42,19890496,8,6,430.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355625,172.217.7.14,80,10.42.0.211,38405.0,6.0,17/06/2017 01:29:11,126711,1,1,0.0,...,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
355626,10.42.0.211,7632,10.42.0.1,53.0,17.0,17/06/2017 01:30:33,48012,1,1,30.0,...,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
355627,10.42.0.211,45970,104.192.110.245,443.0,6.0,17/06/2017 01:29:45,20028018,11,8,339.0,...,20.0,367528.0,0.0,367528.0,367528.0,19660490.0,0.0,19660490.0,19660490.0,Benign
355628,10.42.0.211,51982,10.42.0.1,53.0,17.0,17/06/2017 01:29:45,347926,1,1,32.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
355629,10.42.0.211,9320,10.42.0.1,53.0,17.0,17/06/2017 01:30:33,125473,1,1,30.0,...,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [19]:
def ip_to_decimal(ip):
    # Split the IP address into octets
    octets = ip.split('.')
    # Convert each octet to binary and combine them into a single 32-bit number
    binary = '{0:08b}{1:08b}{2:08b}{3:08b}'.format(*map(int, octets))
    decimal = int(binary, 2) # Convert binary to decimal
    return decimal

In [20]:
dataset['Source IP'] = dataset['Source IP'].apply(ip_to_decimal)
dataset['Destination IP'] = dataset['Destination IP'].apply(ip_to_decimal)

In [21]:
cat_features = ['Source IP', 'Destination IP', 'Source Port', 'Destination Port', 'Protocol']
[cat_features.append(i) for i in dataset.columns if 'Flag' in i]
cat_features

['Source IP',
 'Destination IP',
 'Source Port',
 'Destination Port',
 'Protocol',
 'Fwd PSH Flags',
 'Bwd PSH Flags',
 'Fwd URG Flags',
 'Bwd URG Flags',
 'FIN Flag Count',
 'SYN Flag Count',
 'RST Flag Count',
 'PSH Flag Count',
 'ACK Flag Count',
 'URG Flag Count',
 'ECE Flag Count']

In [22]:
columns_to_drop = dataset.columns[~dataset.any(axis=0) == True].to_list()
dataset.drop(columns=columns_to_drop, inplace=True, errors='ignore')
cat_features = [i for i in cat_features if i not in columns_to_drop]
columns_to_drop

['Bwd PSH Flags',
 'Fwd URG Flags',
 'Bwd URG Flags',
 'RST Flag Count',
 'ECE Flag Count',
 'Fwd Avg Packets/Bulk',
 'Fwd Avg Bulk Rate',
 'Bwd Avg Bytes/Bulk',
 'Bwd Avg Packets/Bulk',
 'Bwd Avg Bulk Rate']

In [23]:
for feature in cat_features:
    dataset[feature] = dataset[feature].astype('object')

dataset['Timestamp'] = pd.to_datetime(dataset['Timestamp'], dayfirst=True)

In [24]:
dataset.describe(include='object')

,Source IP,Source Port,Destination IP,Destination Port,Protocol,Fwd PSH Flags,FIN Flag Count,SYN Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,Label
count,351513,351513,351513,351513.0,351513.0,351513.0,351513.0,351513.0,351513.0,351513.0,351513.0,351513
unique,2533,51341,4743,19407.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,4
top,170524883,443,170524673,443.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,Android_Adware
freq,177261,19601,66792,137034.0,273223.0,328668.0,345618.0,328668.0,235194.0,200248.0,279818.0,147443

In [ ]:
target = 'Label'
X = dataset.drop(columns=target)
y = pd.DataFrame(dataset[target])

dataset.to_parquet('../data/variables/dataset')
X.to_parquet('../data/variables/X')
y.to_parquet('../data/variables/y')

In [ ]:
X_cat = X[cat_features]
X_numeric = X.drop(columns=cat_features + ['Timestamp'])
X_time = pd.DataFrame(X['Timestamp'])

X_cat.to_parquet('../data/variables/X_cat')
X_numeric.to_parquet('../data/variables/X_numeric')
X_time.to_parquet('../data/variables/X_time')